#ifndef ASREPORTLIB_GLOBAL_H
#define ASREPORTLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ASREPORTLIB_LIBRARY)
#  define ASREPORTLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ASREPORTLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ASREPORTLIB_GLOBAL_H
